- genquery.py
Changes corresponding to rei->status fix  [#4157] in msiGetMoreRows.
> [#18] Mods to genquery wrt [irods#4157] (on 4-2-stable)

- genquery.py
Since genQueryOut structure's continueInx flag is (once again) an unambiguous
signal of when to terminate a loop paginating through the results of an iRODS
ICAT general query, the check of msiGetMoreRows's return code against
CAT_NO_ROWS_FOUND is now no longer necessary.
[irods/irods #4157] and this issue [#18] are both addressed by a modification to
msiGetMoreRows, as they apparently arose from the same cause: allowing a negative
value to persist in rei->status (on exit from msiGetMoreRows, when CAT_NO_ROWS_FOUND
was returned from rsGenQuery) actually prevented the update to the continueInx flag
from bubbling up to the microservice's caller, thus preventing its proper monitoring.
This commit contains requisite changes for the genquery.py module's main loop.
That loop, and the …
> [#18] Mods to genquery wrt [irods#4157] (on master)

- README.md
- genquery.py
> Genquery extensions master

- irods_consortium_continuous_integration_build_hook.py
> [#46] added support to install externals from a directory and updated… (master)

- irods_rule_engine_plugin-python.cxx
- irods_types.cpp
#66 cherry-picked into master
Addresses #65
> [#65] Manually include pyconfig.h before features.h can be included (4-2-stable)

- CMakeLists.txt
- irods_consortium_continuous_integration_build_hook.py
- irods_rule_engine_plugin-python.cxx
> [irods/irods_5669, irods/irods_5713] Update for new nlohmann-json

- irods_rule_engine_plugin-python.cxx
> [#96] Do not clearMsParams on error (4-2-stable)

- CMakeLists.txt
- irods_rule_engine_plugin-python.cxx
- irods_rule_engine_plugin-python.hpp
- irods_types.cpp
- irods_types.hpp
Companion PR for irods/irods#6201
Closes irods/irods#5712 for this repo.
In service of irods/irods#6106 and irods/irods#6211.
> [irods/irods#5712, irods/irods#6106, irods/irods#6211] Update for first round of reorganization changes

- irods_consortium_continuous_integration_test_hook.py
adapted from changes made for #112
> [irods/irods#6020] Test hook improvements (4-2-stable)

- irods_rule_engine_plugin-python.cxx
Depends on https://github.com/irods/irods/pull/6332
> Updated for variable renaming (main)

- core.py.template
> [irods/irods_3461] change default server SSL policy to CS_NEG_REFUSE

- CMakeLists.txt
> [#124] Switch to new find module for python

- irods_rule_engine_plugin-python.cxx
> [#131] Change using to namespace for irods logger (main)

- .clang-format
- .github/workflows/linter-irods-clang-format.yml
- .github/workflows/linter-irods-clang-tidy.yml
~Perhaps this repo continues to use spaces.~
~Will think on it.~
This project is small enough that switching to tabs is fine.
> Added .clang-format (main)

- irods_consortium_continuous_integration_build_hook.py
Related: irods/irods_development_environment#107
> [#172] build hook: Use system CMake if newer

- README.md
Added additional time-saving hints about the order of REI stanzas in `/etc/irods/server_config.json`.
> [#178] Add hints about plug-in stanza placement to README.

- README.md
> [#180] Document print behavior in python rules (main)

- include/irods/private/re/python/irods_types.hpp
- src/types/irods/rodsGeneralUpdate.cpp
Addresses #196
Still waiting on the build, but I think this covers everything.
> [#196] Ignore GeneralUpdate deprecation warnings (main)

- include/irods/private/re/python/irods_types.hpp
- src/types/irods/rodsGeneralUpdate.cpp
Addresses #196
Cherry-picked from https://github.com/irods/irods_rule_engine_plugin_python/pull/197
> [#196] Ignore GeneralUpdate deprecation warnings (4-3-stable)

- README.md
> [#187] README: Explain how to pass values back to the caller, across REP boundaries (4-3-stable)

- README.md
- genquery.py
The current implementation works, but it's still a WIP.
> [#182] Add support for GenQuery2 to genquery.py module (4-3-stable)

- README.md
- genquery.py
> [#182] Add support for GenQuery2 to genquery.py module (main)

- irods_consortium_continuous_integration_test_hook.py
> [#221] filter packages in test hook (4-3-stable)

- irods_consortium_continuous_integration_test_hook.py
> [#221] filter packages in test hook (main)

- README.md
> [#227] Fix README example rule (main)

- README.md
Addresses #227
Cherry-pick of #228
> [#227] Fix README example rule (4-3-stable)
